version: "3.8"

services:
  backend:
    build: ./server
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"

  frontend:
    build: ./client
    ports:
      - "8080:80"
    depends_on:
      - backend
  
  db:
    image: mysql:8
    env_file:
      - .env