name: Deploy to QA

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.QA_HOST }}
          username: ${{ secrets.QA_USER }}
          key: ${{ secrets.QA_SSH_KEY }}
          script: |
            cd HelloDevOps
            docker compose -f docker-compose.qa.yml pull
            docker compose -f docker-compose.qa.yml up -d